version: "3"
services:

  app:
    build: ./docker/app
    environment:
      - ISUBATA_DB_HOST=db
      - ISUBATA_DB_PORT=3306
    working_dir: /opt/app
    volumes:
      - opam-data:/root/.opam
      - .:/opt/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    privileged: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=$ISUBATA_DB_USER
      - MYSQL_PASSWORD=$ISUBATA_DB_PASSWORD
      - MYSQL_DATABASE=isubata
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    expose:
      - "3306"

  bench:
    build: ./docker/bench
    environment:
      - ISUBATA_APP_HOST=app
      - ISUBATA_APP_PORT=3000
    depends_on:
      - app

volumes:
  opam-data:
    driver: local