version: "3"
services:

  app:
    build: ./docker/app
    command: >
      dockerize
        -wait tcp://db:3306
        make exec
    environment:
      - ISUBATA_DB_HOST=db
      - ISUBATA_DB_PORT=3306
    working_dir: /opt/app
    volumes:
      - opam-data:/root/.opam
      - .:/opt/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    privileged: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    # command: --max-connections=1000 --max-allowed-packet=512M
    environment:
      - MYSQL_USER=$ISUBATA_DB_USER
      - MYSQL_PASSWORD=$ISUBATA_DB_PASSWORD
      - MYSQL_DATABASE=isubata
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      # - MYSQL_ROOT_PASSWORD=
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    expose:
      - "3306"

  bench:
    build:
      context: ./docker
      dockerfile: Dockerfile-bench
    command: >
      dockerize
        -wait http://app:3000
        -wait-retry-interval 15s
        -timeout 10m
        ./bin/bench -remotes=app:3000 -test
    depends_on:
      - app

volumes:
  opam-data:
    driver: local